"""Configuration types and loading."""

from .loader import ConfigError, ConfigErrorReason, find_config_file, load_config
from .protocol import (
    BtrfsSnapshotConfig,
    Config,
    CredentialProvider,
    EncryptionConfig,
    HardLinkSnapshotConfig,
    LocalVolume,
    LuksEncryptionConfig,
    MountConfig,
    RemoteVolume,
    RsyncOptions,
    SnapshotMode,
    SshEndpoint,
    Slug,
    SshConnectionOptions,
    SyncConfig,
    SyncEndpoint,
    Volume,
)
from nbkp.remote.resolution import (
    EndpointFilter,
    NetworkType,
    ResolvedEndpoint,
    ResolvedEndpoints,
    resolve_all_endpoints,
    resolve_endpoint_for_volume,
    resolve_proxy_chain,
)

__all__ = [
    "BtrfsSnapshotConfig",
    "Config",
    "ConfigError",
    "ConfigErrorReason",
    "CredentialProvider",
    "EncryptionConfig",
    "EndpointFilter",
    "HardLinkSnapshotConfig",
    "LocalVolume",
    "LuksEncryptionConfig",
    "MountConfig",
    "NetworkType",
    "RemoteVolume",
    "RsyncOptions",
    "ResolvedEndpoint",
    "ResolvedEndpoints",
    "SshEndpoint",
    "Slug",
    "SnapshotMode",
    "SshConnectionOptions",
    "SyncConfig",
    "SyncEndpoint",
    "Volume",
    "find_config_file",
    "load_config",
    "resolve_all_endpoints",
    "resolve_endpoint_for_volume",
    "resolve_proxy_chain",
]
