"""Generate the polkit rule for mount management authorization.

udisks is authorized purely by polkit — there is no ``sudo``/sudoers path.
A single rule grants the backup user the udisks actions needed to unlock,
mount, unmount, and lock the configured volumes without an interactive
prompt (required because nbkp runs over SSH / in inactive sessions, where
udisks would otherwise demand admin authentication).

See docs/internals.md § "Why polkit-only".
"""

from __future__ import annotations

from collections.abc import Iterator
from dataclasses import dataclass
from textwrap import dedent

from ..config import Config

# Install path for the generated polkit rule
POLKIT_RULES_PATH = "/etc/polkit-1/rules.d/50-nbkp.rules"

# udisks polkit actions nbkp needs.  The ``-system`` variants cover
# non-removable devices; ``-other-seat`` / ``-others`` cover devices a
# different session unlocked/mounted (e.g. a crypttab boot unlock); the
# ``fstab`` action covers entries carrying ``x-udisks-auth``.
UDISKS_ACTIONS = [
    "org.freedesktop.udisks2.filesystem-mount",
    "org.freedesktop.udisks2.filesystem-mount-system",
    "org.freedesktop.udisks2.filesystem-mount-other-seat",
    "org.freedesktop.udisks2.filesystem-fstab",
    "org.freedesktop.udisks2.filesystem-unmount-others",
    "org.freedesktop.udisks2.encrypted-unlock",
    "org.freedesktop.udisks2.encrypted-unlock-system",
    "org.freedesktop.udisks2.encrypted-lock-others",
]


@dataclass(frozen=True)
class AuthRuleBlock:
    """A single auth-rule file to install: human name, target path, body."""

    name: str
    path: str
    content: str

    @property
    def install_hint(self) -> str:
        """Single-line "Install to: <path>" hint used in user-facing output."""
        return f"Install to: {self.path}"


@dataclass(frozen=True)
class AuthRules:
    """Generated authorization rules for mount management."""

    polkit: str | None
    """polkit rules content, or None if no volumes have mount config."""

    def polkit_block(self) -> AuthRuleBlock | None:
        """Polkit block, or None when no polkit rules were generated."""
        if self.polkit:
            return AuthRuleBlock("polkit rules", POLKIT_RULES_PATH, self.polkit)
        return None

    def blocks(self) -> Iterator[AuthRuleBlock]:
        """Yield each non-empty auth-rule block in install order."""
        polkit = self.polkit_block()
        if polkit is not None:
            yield polkit


def generate_polkit_rules(user: str) -> str:
    """Generate the polkit rule granting *user* the udisks mount actions."""
    actions_js = ", ".join(f'"{a}"' for a in UDISKS_ACTIONS)
    return dedent(f"""\
        // Generated by nbkp disks setup-auth
        // Install to: {POLKIT_RULES_PATH}
        var nbkpActions = [{actions_js}];
        polkit.addRule(function(action, subject) {{
            if (subject.user == "{user}" &&
                nbkpActions.indexOf(action.id) > -1) {{
                return polkit.Result.YES;
            }}
        }});
    """)


def generate_auth_rules(config: Config, user: str) -> AuthRules:
    """Generate the polkit rule for all volumes with mount config.

    A single rule covers every mount-managed volume (the udisks actions are
    not device-specific), so the result is non-empty whenever at least one
    volume declares a ``mount`` section.
    """
    has_mount = any(
        getattr(vol, "mount", None) is not None for vol in config.volumes.values()
    )
    return AuthRules(polkit=generate_polkit_rules(user) if has_mount else None)
