"""Auto-generate configuration reference documentation from Pydantic models.

Introspects the config protocol models and generates docs/config-reference.md
with field tables and hand-written prose sections. Use --check to verify the
docs are up to date.

Usage:
    python build-scripts/configdocs.py          # regenerate docs/config-reference.md
    python build-scripts/configdocs.py --check  # exit non-zero if out of date
"""

from __future__ import annotations

import sys
from pathlib import Path
from typing import Annotated, Any, get_args, get_origin

import typer
from pydantic import BaseModel
from pydantic.fields import FieldInfo

CONFIG_REFERENCE_MD = Path("docs/config-reference.md")
HEADER = "<!-- AUTO-GENERATED by: mise run configdocs — do not edit manually -->"


# ---------------------------------------------------------------------------
# Prose sections (hand-written content embedded in the generator)
# ---------------------------------------------------------------------------

_TOP_LEVEL_STRUCTURE = """\
```yaml
ssh-endpoints:
  <slug>: <SshEndpoint>

volumes:
  <slug>: <LocalVolume | RemoteVolume>

sync-endpoints:
  <slug>: <SyncEndpoint>

syncs:
  <slug>: <SyncConfig>
```

Slugs must be lowercase alphanumeric with hyphens (e.g. `my-nas`, `usb-drive`). Max 50 characters."""

_SSH_ENDPOINT_NOTES = "Fields not explicitly set (`port`, `user`, `key`) are automatically filled from `~/.ssh/config`. See [SSH Endpoints](./concepts.md#ssh-endpoints)."

_LOCAL_VOLUME_NOTES = '> **YAML caveat:** Bare `~` is interpreted as `null` by YAML. Always quote it: `path: "~"` or `path: "~/subdir"`.'

_SYNC_ENDPOINT_NOTES = """\
Only one of `btrfs-snapshots` and `hard-link-snapshots` can be enabled per endpoint. Each (volume, subdir) pair must be unique across all sync endpoints.

When used as a **source**, enabling snapshots tells rsync to read from the `latest/` directory instead of the volume root. When used as a **destination**, enabling snapshots activates snapshot creation after each successful sync."""

_SYNC_CONFIG_NOTES = "Each destination endpoint can only be used by one sync (no two syncs may share the same destination)."

_RSYNC_OPTIONS_NOTES = """\
Default rsync flags (when `default-options-override` is not set):

```
-a --delete --delete-excluded --partial-dir=.rsync-partial --safe-links
```"""

_FILTERS_SECTION = """\
### Filters

Filters can be specified as structured rules or raw rsync filter strings, mixed freely:

```yaml
filters:
  # Structured include/exclude rules
  - include: "*.jpg"          # becomes "+ *.jpg"
  - exclude: "*.tmp"          # becomes "- *.tmp"

  # Merge: read rules from an external file (applied globally)
  - merge: /etc/nbkp/extra-rules.txt
  - merge: ~/my-rules.txt    # tilde is expanded

  # Dir-merge: per-directory filter files (rsync discovers them as it walks the tree)
  - dir-merge: .rsync-filter

  # Dir-merge with exclude-self: equivalent to rsync's -FF
  # (use per-directory filters, but don't transfer the filter files themselves)
  - dir-merge:
      path: .rsync-filter
      exclude-self: true

  # Raw rsync filter strings (for advanced modifiers like ,e or ,n)
  - "H .git"                  # hide .git from transfer
  - "- __pycache__/"          # exclude __pycache__
  - "dir-merge,e /.rsync-filter"  # dir-merge with word-splitting
```

**`merge`** reads a file of filter rules once and applies them at the point where they appear in the list. Tilde (`~`) is expanded in merge paths. This is similar to `filter-file`, but `filter-file` is always appended after all inline filters, while `merge` respects its position in the list.

**`dir-merge`** tells rsync to look for the named file in each directory as it walks the source tree. Rules from each file apply only to that directory and its subdirectories. The `exclude-self` option appends a `- <filename>` rule to prevent the filter files from being transferred (equivalent to rsync's `-FF` flag). Dir-merge paths are not tilde-expanded (they are relative filenames resolved by rsync per-directory).

Filters are applied in order as `--filter=RULE` arguments. When `filter-file` is also set, inline filters are applied first."""


# ---------------------------------------------------------------------------
# Field introspection helpers
# ---------------------------------------------------------------------------

# Fields auto-injected by validators, not part of the user-facing config
_HIDDEN_FIELDS = {"slug"}

# Discriminator fields that should show as **required** with a description
_DISCRIMINATOR_OVERRIDES: dict[str, tuple[str, str]] = {
    "type": ("**required**", "Volume type discriminator"),
}


def _to_kebab(name: str) -> str:
    return name.replace("_", "-")


def _constraints_str(info: FieldInfo) -> str:
    """Extract constraint annotations (ge, le) from field metadata."""
    constraints: list[str] = []
    if info.metadata:
        for m in info.metadata:
            if hasattr(m, "ge") and m.ge is not None:
                constraints.append(f">= {m.ge}")
            if hasattr(m, "le") and m.le is not None:
                constraints.append(f"<= {m.le}")
    return f" ({', '.join(constraints)})" if constraints else ""


def _type_str(info: FieldInfo) -> str:
    """Human-readable type string for a field."""
    annotation = info.annotation
    if annotation is None:
        return "any"

    origin = get_origin(annotation)
    args = get_args(annotation)

    # Optional[X] → show the inner type with original constraints
    from types import UnionType

    if origin in (type(None),) or origin is UnionType:
        non_none = [a for a in args if a is not type(None)]
        if len(non_none) == 1:
            # Pass original info to preserve constraints
            inner_info = FieldInfo(annotation=non_none[0])
            inner_info.metadata = info.metadata
            return _type_str(inner_info)

    # Literal
    from typing import Literal

    if origin is Literal:
        return " \\| ".join(f'`"{a}"`' for a in args)

    # List[X]
    if origin is list:
        if args:
            inner_info = FieldInfo(annotation=args[0])
            return f"list of {_type_str(inner_info)}s"
        return "list"

    # Dict
    if origin is dict:
        return "object"

    # Pydantic model (nested)
    if isinstance(annotation, type) and issubclass(annotation, BaseModel):
        return "object"

    # Basic types
    type_map: dict[type[Any], str] = {
        str: "string",
        int: "integer",
        float: "float",
        bool: "boolean",
    }
    if annotation in type_map:
        return type_map[annotation] + _constraints_str(info)

    return str(annotation)


def _default_str(info: FieldInfo) -> str:
    """Human-readable default for a field."""
    if info.is_required():
        return "**required**"

    default = info.default
    if default is None:
        return "`null`"
    if isinstance(default, bool):
        return f"`{str(default).lower()}`"
    if isinstance(default, (int, float)):
        return f"`{default}`"
    if isinstance(default, str):
        return f'`"{default}"`'
    if isinstance(default, list) and len(default) == 0:
        return "`[]`"

    # default_factory
    if info.default_factory is not None:
        factory_result = info.default_factory()
        if isinstance(factory_result, BaseModel):
            return "see below"
        if isinstance(factory_result, list) and len(factory_result) == 0:
            return "`[]`"
        return str(factory_result)

    return str(default)


def _generate_table(model: type[BaseModel]) -> str:
    """Generate a markdown table from a Pydantic model's fields."""
    rows = ["| Field | Type | Default | Description |", "|---|---|---|---|"]
    for name, info in model.model_fields.items():
        if name in _HIDDEN_FIELDS:
            continue
        field_name = f"`{_to_kebab(name)}`"
        if name in _DISCRIMINATOR_OVERRIDES:
            override_default, override_desc = _DISCRIMINATOR_OVERRIDES[name]
            field_type = _type_str(info)
            rows.append(
                f"| {field_name} | {field_type} | {override_default} | {override_desc} |"
            )
        else:
            field_type = _type_str(info)
            field_default = _default_str(info)
            field_desc = info.description or ""
            rows.append(
                f"| {field_name} | {field_type} | {field_default} | {field_desc} |"
            )
    return "\n".join(rows)


# ---------------------------------------------------------------------------
# Document assembly
# ---------------------------------------------------------------------------


def _generate_config_reference() -> str:
    """Generate the full config-reference.md content."""
    from nbkp.config.protocol.ssh_endpoint import SshConnectionOptions, SshEndpoint
    from nbkp.config.protocol.sync import RsyncOptions, SyncConfig
    from nbkp.config.protocol.sync_endpoint import (
        BtrfsSnapshotConfig,
        SyncEndpoint,
    )
    from nbkp.config.protocol.volume import LocalVolume, RemoteVolume

    sections: list[str] = [
        "# Configuration Reference",
        "",
        "## Top-level structure",
        "",
        _TOP_LEVEL_STRUCTURE,
        "",
        "---",
        "",
        f"## `ssh-endpoints.<slug>` — SSH Endpoint",
        "",
        _generate_table(SshEndpoint),
        "",
        _SSH_ENDPOINT_NOTES,
        "",
        "---",
        "",
        f"## `connection-options` — SSH Connection Options",
        "",
        _generate_table(SshConnectionOptions),
        "",
        "---",
        "",
        f"## `volumes.<slug>` — Local Volume",
        "",
        _generate_table(LocalVolume),
        "",
        _LOCAL_VOLUME_NOTES,
        "",
        f"## `volumes.<slug>` — Remote Volume",
        "",
        _generate_table(RemoteVolume),
        "",
        "---",
        "",
        f"## `sync-endpoints.<slug>` — Sync Endpoint",
        "",
        _generate_table(SyncEndpoint),
        "",
        _SYNC_ENDPOINT_NOTES,
        "",
        "---",
        "",
        f"## `syncs.<slug>` — Sync Config",
        "",
        _generate_table(SyncConfig),
        "",
        _SYNC_CONFIG_NOTES,
        "",
        "---",
        "",
        f"## `btrfs-snapshots` / `hard-link-snapshots`",
        "",
        _generate_table(BtrfsSnapshotConfig),
        "",
        "---",
        "",
        f"## `rsync-options` — Rsync Options",
        "",
        _generate_table(RsyncOptions),
        "",
        _RSYNC_OPTIONS_NOTES,
        "",
        "---",
        "",
        _FILTERS_SECTION,
    ]

    return "\n".join(sections)


def _build_file(generated: str) -> str:
    """Build the full file content with header."""
    return f"{HEADER}\n\n{generated}\n"


app = typer.Typer(add_completion=False)


@app.command()
def main(
    check: Annotated[
        bool,
        typer.Option(
            "--check", help="Check that docs are up to date (exit non-zero if not)"
        ),
    ] = False,
) -> None:
    """Generate or check config reference documentation."""
    generated = _generate_config_reference()
    expected = _build_file(generated)

    if check:
        current = (
            CONFIG_REFERENCE_MD.read_text() if CONFIG_REFERENCE_MD.exists() else ""
        )
        if current == expected:
            print("Config reference is up to date.")
        else:
            print(
                f"Config reference in {CONFIG_REFERENCE_MD} is out of date.\n"
                "Run `mise run configdocs` to regenerate.",
                file=sys.stderr,
            )
            sys.exit(1)
    else:
        CONFIG_REFERENCE_MD.write_text(expected)
        print(f"Updated {CONFIG_REFERENCE_MD}")


if __name__ == "__main__":
    app()
